export default function OfficeManagerJobDescription() {
return <main className="doc"><style>{`
.doc{max-width:900px;margin:0 auto;padding:44px;font-family:Arial,sans-serif;color:#334155}.header{border-top:8px solid #6e5084;padding-top:24px}.label{color:#8a6a9e;font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}h1{color:#33283a;font-size:34px;margin:8px 0 24px}.summary{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:#e8dfeb;border:1px solid #e8dfeb}.cell{background:#f7f1fc;padding:14px}.cell b{display:block;color:#6e5084;font-size:12px;margin-bottom:5px}h2{color:#6e5084;font-size:19px;margin-top:28px;border-bottom:1px solid #e8dfeb;padding-bottom:7px}li{margin:8px 0;line-height:1.5}.note{margin-top:30px;padding:16px;background:#f5fff9;border:1px solid #dcece4}
`}</style><div className="header"><div className="label">LEO HR · Job Description</div><h1>Office Manager</h1></div>
<div className="summary"><div className="cell"><b>REPORTS TO</b>Managing Director</div><div className="cell"><b>DEPARTMENT</b>Administration</div><div className="cell"><b>LOCATION</b>[Insert location]</div><div className="cell"><b>WORKING HOURS</b>[Insert hours]</div></div>
<h2>Role Purpose</h2><p>To keep the day-to-day office running smoothly, provide reliable administrative support and help create an organised, professional working environment.</p>
<h2>Key Responsibilities</h2><ul><li>Coordinate day-to-day office administration, supplies, facilities and routine services.</li><li>Maintain accurate records, calendars and business documentation.</li><li>Support managers with meetings, correspondence and administrative tasks.</li><li>Act as a professional first point of contact for visitors, suppliers and general enquiries.</li><li>Coordinate office procedures and identify practical improvements.</li><li>Handle business information appropriately and maintain confidentiality.</li></ul>
<h2>Person Requirements</h2><ul><li>Strong organisation and prioritisation skills.</li><li>Clear written and verbal communication.</li><li>Confident using common office software and systems.</li><li>Reliable, discreet and comfortable working independently.</li><li>Previous administration or office coordination experience is desirable.</li></ul>
<h2>Review</h2><p>This job description describes the main requirements of the role. Duties may reasonably develop as the organisation changes and should be reviewed with the employee where material changes are proposed.</p>
<div className="note"><b>LEO practical note:</b> Adapt responsibilities and person requirements to the genuine needs of the role. Avoid criteria that are unnecessary or could create unjustified barriers for applicants.</div></main>}
