import { NextRequest, NextResponse } from "next/server";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import { resolveRoleForMembership } from "@/lib/auth/authoritativeRoleResolver";
import { createClient } from "@/lib/supabase/server";
type RouteContext={params:Promise<{id:string}>}; export const dynamic="force-dynamic";
function adminClient(){const u=process.env.NEXT_PUBLIC_SUPABASE_URL,k=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!u||!k)throw new Error("Supabase administrator credentials are not configured.");return createAdminClient(u,k,{auth:{autoRefreshToken:false,persistSession:false}})}
async function ctx(context:RouteContext,permission:"employees.view"|"employees.manage"){
 const {id}=await context.params;const employeeId=Number(id);if(!Number.isInteger(employeeId)||employeeId<=0)return{response:NextResponse.json({success:false,error:"The employee reference is not valid."},{status:400})};
 const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return{response:NextResponse.json({success:false,error:"You are not signed in."},{status:401})};
 const {data:organisationId}=await supabase.rpc("leo_current_organisation_id");if(typeof organisationId!=="string"||!organisationId)return{response:NextResponse.json({success:false,error:"Your active organisation could not be resolved."},{status:403})};
 const {data:m}=await supabase.from("organisation_memberships").select("id,role").eq("organisation_id",organisationId).eq("user_id",user.id).eq("membership_status","active").maybeSingle();if(!m)return{response:NextResponse.json({success:false,error:"You do not have active access to this organisation."},{status:403})};
 const role=await resolveRoleForMembership(supabase as any,{membershipId:m.id,fallbackRole:m.role});if(role.roleKey!=="owner"){const {data:p}=await supabase.rpc("leo_effective_permissions",{target_organisation_id:organisationId});const keys=new Set((p??[]).map((x:any)=>x?.permission_key).filter(Boolean));if(!keys.has(permission))return{response:NextResponse.json({success:false,error:"You do not have permission to perform this employee action."},{status:403})}}
 const admin=adminClient();const {data:employee}=await admin.from("employees").select("id").eq("id",employeeId).eq("organisation_id",organisationId).maybeSingle();if(!employee)return{response:NextResponse.json({success:false,error:"The employee record could not be found or accessed."},{status:404})};return{employeeId,admin};
}
const fields="id,drives_for_work,vehicle_used,authorised_to_drive,driving_licence_number,licence_categories,licence_issue_date,licence_expiry_date,dvla_check_completed,dvla_check_date,next_dvla_check_due,business_insurance_confirmed,business_insurance_expiry_date,penalty_points,motoring_convictions,restrictions_or_adjustments,senior_authorisation_required,authorised_by,date_authorised,notes,created_at";
export async function GET(_r:NextRequest,c:RouteContext){try{const x=await ctx(c,"employees.view");if("response"in x)return x.response;const {data,error}=await x.admin.from("employee_driving_checks").select(fields).eq("employee_id",x.employeeId).order("created_at",{ascending:false});if(error)throw new Error(error.message);return NextResponse.json({success:true,records:data??[]},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error("Employee driving API failed:",e);return NextResponse.json({success:false,error:e instanceof Error?e.message:"Driving records could not be loaded."},{status:500})}}
export async function POST(r:NextRequest,c:RouteContext){try{const x=await ctx(c,"employees.manage");if("response"in x)return x.response;const b=await r.json(),yes=b.drivesForWork==="Yes";const {error}=await x.admin.from("employee_driving_checks").insert({employee_id:x.employeeId,drives_for_work:b.drivesForWork||"No",vehicle_used:yes?b.vehicleUsed||null:null,authorised_to_drive:yes?b.authorisedToDrive||null:null,driving_licence_number:yes?b.drivingLicenceNumber||null:null,licence_categories:yes?b.licenceCategories||null:null,licence_issue_date:yes?b.licenceIssueDate||null:null,licence_expiry_date:yes?b.licenceExpiryDate||null:null,dvla_check_completed:yes?b.dvlaCheckCompleted||null:null,dvla_check_date:yes?b.dvlaCheckDate||null:null,next_dvla_check_due:yes?b.nextDvlaCheckDue||null:null,business_insurance_confirmed:yes?b.businessInsuranceConfirmed||null:null,business_insurance_expiry_date:yes?b.businessInsuranceExpiryDate||null:null,penalty_points:yes?b.penaltyPoints??null:null,motoring_convictions:yes?b.motoringConvictions||null:null,restrictions_or_adjustments:yes?b.restrictionsOrAdjustments||null:null,senior_authorisation_required:yes?b.seniorAuthorisationRequired||null:null,authorised_by:yes?b.authorisedBy||null:null,date_authorised:yes?b.dateAuthorised||null:null,notes:b.notes||null,updated_at:new Date().toISOString()});if(error)throw new Error(error.message);return NextResponse.json({success:true})}catch(e){console.error("Employee driving save failed:",e);return NextResponse.json({success:false,error:e instanceof Error?e.message:"Driving record could not be saved."},{status:500})}}
