import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

type RouteContext = { params: Promise<{ id: string; documentId: string }> };
function text(value: unknown): string { return typeof value === "string" ? value.trim() : ""; }
async function organisationIdForUser(supabase: any) { const { data: { user } } = await supabase.auth.getUser(); if (!user) return null; const membership = await supabase.from("organisation_memberships").select("organisation_id").eq("user_id", user.id).eq("membership_status", "active").order("is_default_organisation", { ascending: false }).limit(1).maybeSingle(); return membership.data?.organisation_id ?? null; }
export async function GET(_request: Request, context: RouteContext) {
  try { const { id, documentId } = await context.params; const supabase = await createClient(); const organisationId = await organisationIdForUser(supabase as any); if (!organisationId) return NextResponse.json({ success: false, error: "Your organisation access could not be verified." }, { status: 403 }); const result = await (supabase as any).from("leo_talent_candidate_documents").select("id, candidate_id, file_path, file_name").eq("id", documentId).eq("candidate_id", id).eq("organisation_id", organisationId).maybeSingle(); if (result.error) throw new Error(result.error.message); if (!result.data) return NextResponse.json({ success: false, error: "The candidate document was not found." }, { status: 404 }); const signed = await (supabase as any).storage.from("leo-talent-candidate-documents").createSignedUrl(result.data.file_path, 60); if (signed.error || !signed.data?.signedUrl) throw new Error(signed.error?.message || "Leo could not create a secure document link."); return NextResponse.json({ success: true, url: signed.data.signedUrl, fileName: result.data.file_name }); } catch (error) { console.error("Candidate document open failed:", error); return NextResponse.json({ success: false, error: error instanceof Error ? error.message : "Leo could not open this candidate document." }, { status: 500 }); }
}
export async function DELETE(_request: Request, context: RouteContext) {
  try { const { id, documentId } = await context.params; const supabase = await createClient(); const organisationId = await organisationIdForUser(supabase as any); if (!organisationId) return NextResponse.json({ success: false, error: "Your organisation access could not be verified." }, { status: 403 }); const result = await (supabase as any).from("leo_talent_candidate_documents").select("id, file_path").eq("id", documentId).eq("candidate_id", id).eq("organisation_id", organisationId).maybeSingle(); if (result.error) throw new Error(result.error.message); if (!result.data) return NextResponse.json({ success: false, error: "The candidate document was not found." }, { status: 404 }); const removed = await (supabase as any).storage.from("leo-talent-candidate-documents").remove([text(result.data.file_path)]); if (removed.error) throw new Error(removed.error.message); const deleted = await (supabase as any).from("leo_talent_candidate_documents").delete().eq("id", documentId).eq("candidate_id", id).eq("organisation_id", organisationId); if (deleted.error) throw new Error(deleted.error.message); return NextResponse.json({ success: true }); } catch (error) { return NextResponse.json({ success: false, error: error instanceof Error ? error.message : "Leo could not delete this candidate document." }, { status: 500 }); }
}