import { NextRequest,NextResponse } from "next/server";import{createClient as adminCreate}from"@supabase/supabase-js";import{createClient}from"@/lib/supabase/server";import{resolveRoleForMembership}from"@/lib/auth/authoritativeRoleResolver";
type C={params:Promise<{id:string}>};export const dynamic="force-dynamic";
export async function GET(_r:NextRequest,c:C){try{const{id}=await c.params,employeeId=Number(id);if(!Number.isInteger(employeeId))return NextResponse.json({success:false,error:"Invalid employee."},{status:400});const s=await createClient(),{data:{user}}=await s.auth.getUser();if(!user)return NextResponse.json({success:false,error:"You are not signed in."},{status:401});const{data:o}=await s.rpc("leo_current_organisation_id");if(typeof o!=="string"||!o)return NextResponse.json({success:false,error:"Organisation unavailable."},{status:403});const{data:m}=await s.from("organisation_memberships").select("id,role").eq("organisation_id",o).eq("user_id",user.id).eq("membership_status","active").maybeSingle();if(!m)return NextResponse.json({success:false,error:"Access denied."},{status:403});const role=await resolveRoleForMembership(s as any,{membershipId:m.id,fallbackRole:m.role});if(role.roleKey!=="owner"){const{data:p}=await s.rpc("leo_effective_permissions",{target_organisation_id:o});if(!(p??[]).some((x:any)=>x?.permission_key==="employees.view"))return NextResponse.json({success:false,error:"Access denied."},{status:403})}const url=process.env.NEXT_PUBLIC_SUPABASE_URL,key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key)throw new Error("Server configuration unavailable.");const a=adminCreate(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const{data:e}=await a.from("employees").select("id").eq("id",employeeId).eq("organisation_id",o).maybeSingle();if(!e)return NextResponse.json({success:false,error:"Employee unavailable."},{status:404});
const [rt,dbs,driving,training,leave,employment]=await Promise.all([
a.from("employee_right_to_work").select("right_to_work_expiry,next_review_date").eq("employee_id",employeeId).order("created_at",{ascending:false}).limit(1),
a.from("employee_dbs_checks").select("next_check_due,safeguarding_training_expiry").eq("employee_id",employeeId).order("created_at",{ascending:false}).limit(1),
a.from("employee_driving_checks").select("licence_expiry_date,next_dvla_check_due,business_insurance_expiry_date").eq("employee_id",employeeId).order("created_at",{ascending:false}).limit(1),
a.from("employee_training_logs").select("training_name,refresh_or_expiry_date").eq("employee_id",employeeId).order("refresh_or_expiry_date",{ascending:true}),
a.from("employee_leave_records").select("leave_type,status,days_taken").eq("employee_id",employeeId),
a.from("employee_employment_details").select("annual_leave_allowance").eq("employee_id",employeeId).maybeSingle()
]);for(const x of [rt,dbs,driving,training,leave,employment])if(x.error)throw new Error(x.error.message);const allowance=Number(employment.data?.annual_leave_allowance||0);const used=(leave.data||[]).filter((x:any)=>x.leave_type==="Annual Leave"&&x.status!=="Cancelled").reduce((n:number,x:any)=>n+Number(x.days_taken||0),0);return NextResponse.json({success:true,rightToWork:rt.data?.[0]||null,dbs:dbs.data?.[0]||null,driving:driving.data?.[0]||null,training:training.data||[],annualLeaveAllowance:allowance,annualLeaveUsed:used},{headers:{"Cache-Control":"no-store"}})}catch(e){console.error("Compliance summary API failed:",e);return NextResponse.json({success:false,error:"Compliance records could not be loaded."},{status:500})}}
