"use client";
import {useState} from "react";
import styles from "../../employer-support-portal.module.css";
type Action={id:number;title:string;detail?:string|null;status:string};
export default function MatterActions({matterId,initialActions}:{matterId:number;initialActions:Action[]}){
 const [actions,setActions]=useState(initialActions);const [busy,setBusy]=useState<number|null>(null);const [adding,setAdding]=useState(false);const [showAdd,setShowAdd]=useState(false);const [title,setTitle]=useState("");const [detail,setDetail]=useState("");const [error,setError]=useState("");
 async function toggle(a:Action){setBusy(a.id);setError("");try{const status=a.status==="done"?"open":"done";const r=await fetch(`/api/employer-support/matters/${matterId}/actions`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({actionId:a.id,status})});if(!r.ok)throw new Error("The action could not be updated.");setActions(v=>v.map(x=>x.id===a.id?{...x,status}:x));}catch(e){setError(e instanceof Error?e.message:"The action could not be updated.");}finally{setBusy(null)}}
 async function add(){const cleanTitle=title.trim();if(!cleanTitle)return;setAdding(true);setError("");try{const r=await fetch(`/api/employer-support/matters/${matterId}/actions/create`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:cleanTitle,detail:detail.trim()})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"The action could not be added.");setActions(v=>[...v,p.action]);setTitle("");setDetail("");setShowAdd(false);}catch(e){setError(e instanceof Error?e.message:"The action could not be added.");}finally{setAdding(false)}}
 return <section className={styles.actionPanel}><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Next steps</p><h2>Actions for this matter</h2></div><div className={styles.panelControls}><span>{actions.filter(a=>a.status==="open").length} open</span><button type="button" onClick={()=>setShowAdd(v=>!v)} disabled={adding}>{showAdd?"Cancel":"+ Add step"}</button></div></div>
 {showAdd?<div className={styles.inlineActionForm}><label>What needs to happen next?<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Speak to the employee separately" autoFocus/></label><label>Note <span>(optional)</span><textarea value={detail} onChange={e=>setDetail(e.target.value)} placeholder="Add any useful detail" rows={2}/></label><button type="button" onClick={add} disabled={adding||!title.trim()}>{adding?"Adding…":"Add action"}</button></div>:null}
 {error?<p className={styles.chatError}>{error}</p>:null}
 {actions.length?<div className={styles.actionList}>{actions.map(a=><button key={a.id} onClick={()=>toggle(a)} disabled={busy===a.id} className={a.status==="done"?styles.actionDone:styles.actionRow}><i>{a.status==="done"?"✓":"○"}</i><span><strong>{a.title}</strong>{a.detail?<small>{a.detail}</small>:null}</span></button>)}</div>:<div className={styles.softEmpty}><span>✓</span><div><strong>No actions at the moment</strong><small>Actions agreed while working with Leo will appear here.</small></div></div>}
 </section>
}