"use client";
import {useState} from "react";
import styles from "../../employer-support-portal.module.css";
type Doc={id:number;title:string;document_type:string;status:string;source?:string|null;file_name?:string|null;hasFile?:boolean;created_at:string};
export default function MatterDocuments({matterId,documents,closed=false}:{matterId:number;documents:Doc[];closed?:boolean}){
 const [open,setOpen]=useState(false);const [openingId,setOpeningId]=useState<number|null>(null);const [error,setError]=useState("");const [draft,setDraft]=useState<{id:number;title:string;content:string;closed:boolean}|null>(null);const drafts=documents.filter(d=>d.status==="Draft"&&d.source==="leo_generated");
 async function openDocument(documentId:number){setOpeningId(documentId);setError("");try{const r=await fetch(`/api/employer-support/matters/${matterId}/documents/${documentId}/open`);const p=await r.json().catch(()=>({}));if(!r.ok||!p.url)throw new Error(p.error||"The document could not be opened.");const opened=window.open(p.url,"_blank","noopener,noreferrer");if(!opened)window.location.assign(p.url);}catch(e){setError(e instanceof Error?e.message:"The document could not be opened.");}finally{setOpeningId(null)}}
 async function reviewDraft(documentId:number){setOpeningId(documentId);setError("");try{const r=await fetch(`/api/employer-support/matters/${matterId}/documents/${documentId}/draft`,{cache:"no-store"});const p=await r.json().catch(()=>({}));if(!r.ok||!p.document)throw new Error(p.error||"The draft could not be loaded.");setDraft({id:p.document.id,title:p.document.title,content:p.document.content,closed:Boolean(p.document.closed)});}catch(e){setError(e instanceof Error?e.message:"The draft could not be loaded.");}finally{setOpeningId(null)}}
 return <section className={styles.documentPanel}><div className={styles.panelHeading}><div><p className={styles.eyebrow}>Documents</p><h2>Documents and evidence</h2></div>{documents.length>3?<button type="button" className={styles.textButton} onClick={()=>setOpen(v=>!v)}>{open?"Show less":"View all"}</button>:null}</div>
 {closed&&documents.some(d=>d.status==="Draft")?<p className={styles.draftReminder}>This matter is closed. Draft documents remain part of the record and cannot be changed here.</p>:null}
 {documents.length?<div className={styles.documentList}>{documents.slice(0,open?documents.length:3).map(d=><div key={d.id} className={styles.documentRow}><span className={d.status==="Draft"?styles.draftIcon:styles.fileIcon}>{d.status==="Draft"?"✎":"↥"}</span><div><strong>{d.title}</strong><small>{d.document_type} · {d.status} · {new Date(d.created_at).toLocaleDateString("en-GB")}</small></div><div className={styles.documentActions}>{d.status==="Draft"&&d.source==="leo_generated"?<button type="button" onClick={()=>reviewDraft(d.id)} disabled={openingId===d.id}>{openingId===d.id?"Opening…":"Review"}</button>:d.hasFile?<button type="button" onClick={()=>openDocument(d.id)} disabled={openingId===d.id}>{openingId===d.id?"Opening…":"Open"}</button>:null}<em>{d.status==="Draft"&&d.source==="leo_generated"?"Review before use":d.hasFile?"Evidence":"Record"}</em></div></div>)}</div>:<div className={styles.softEmpty}><span>↥</span><div><strong>No documents yet</strong><small>Upload relevant evidence or documents for this matter.</small></div></div>}
 {draft?<div className={styles.draftReview}><div className={styles.draftReviewHeader}><div><span>Draft correspondence</span><strong>{draft.title}</strong></div><div className={styles.draftReviewActions}><a href={`/api/employer-support/matters/${matterId}/documents/${draft.id}/word`}>Download Word draft</a><button type="button" onClick={()=>setDraft(null)}>Close</button></div></div><div className={styles.draftPaper}>{draft.content.split(/\n/).map((line,i)=>line.trim()?<p key={i}>{line}</p>:<br key={i}/>)}</div><p className={styles.draftReviewNote}>{draft.closed?"This matter is closed. This draft is retained as part of the record and is read-only.":"Review all names, dates, facts and placeholders carefully before using this correspondence."}</p></div>:null}
 {error?<p className={styles.chatError}>{error}</p>:null}
 {drafts.length>0&&!closed?<p className={styles.draftReminder}>Documents prepared by Leo remain drafts until you review and use them.</p>:null}
 </section>
}