export default function SalesExecutiveJobDescription() {
return <main className="doc"><style>{`
.doc{max-width:900px;margin:0 auto;padding:44px;font-family:Arial,sans-serif;color:#334155}.hero{background:#f7f1fc;border-left:7px solid #6e5084;padding:26px 28px}.label{color:#8a6a9e;font-size:12px;font-weight:700;letter-spacing:.12em;text-transform:uppercase}h1{margin:7px 0;color:#33283a;font-size:34px}.purpose{font-size:17px;line-height:1.55}.facts{display:flex;gap:24px;flex-wrap:wrap;margin-top:18px;color:#6e5084;font-weight:700;font-size:13px}h2{color:#6e5084;margin-top:30px;font-size:19px}.outcomes{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.outcome{padding:16px;border:1px solid #e8dfeb;border-radius:10px}.outcome b{display:block;color:#33283a;margin-bottom:6px}li{margin:8px 0;line-height:1.5}.measure{padding:16px 18px;background:#f5fff9;border:1px solid #dcece4;margin-top:12px}
`}</style><section className="hero"><div className="label">LEO HR · Job Description</div><h1>Sales Executive</h1><p className="purpose">Build new customer relationships, understand commercial needs and convert suitable opportunities into sustainable sales.</p><div className="facts"><span>Reports to: Sales Manager</span><span>Location: [Insert]</span><span>Hours: [Insert]</span></div></section>
<h2>What Success Looks Like</h2><div className="outcomes"><div className="outcome"><b>Pipeline</b>Maintain a healthy, accurate pipeline of suitable opportunities.</div><div className="outcome"><b>Customers</b>Build professional relationships and understand customer needs.</div><div className="outcome"><b>Results</b>Work towards agreed, reasonable sales objectives and quality standards.</div></div>
<h2>Core Responsibilities</h2><ul><li>Identify and develop prospective customer opportunities.</li><li>Conduct discovery conversations and explain relevant products or services accurately.</li><li>Prepare proposals, follow up opportunities and maintain clear CRM records.</li><li>Work collaboratively with colleagues to support a positive customer experience.</li><li>Keep product, market and competitor knowledge current.</li><li>Follow applicable company policies, sales standards and data protection requirements.</li></ul>
<h2>Skills & Experience</h2><ul><li>Confident communication and relationship-building skills.</li><li>Commercial awareness and a customer-focused approach.</li><li>Ability to organise a pipeline and follow through on commitments.</li><li>Sales experience is desirable; relevant transferable experience may also be suitable.</li></ul>
<h2>Success Measures</h2><div className="measure">Measures should be set separately and reviewed regularly. They may include appropriate activity, pipeline quality, conversion, revenue and customer outcomes. Targets should reflect the role and business context.</div>
<h2>Role Flexibility</h2><p>The responsibilities above describe the role at the date of issue. Reasonable changes may be made as business needs develop, following appropriate discussion where changes are material.</p></main>}
