-- Ask Leo conversation persistence (separate from Matters)

create table if not exists public.ask_leo_conversations (
  id bigint generated by default as identity primary key,
  organisation_id uuid not null,
  user_id uuid not null,
  title text not null,
  last_message_preview text not null default '',
  last_message_at timestamptz not null default now(),
  converted_to_matter_id bigint null,
  converted_to_matter_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ask_leo_conversations_title_not_blank check (length(trim(title)) > 0),
  constraint ask_leo_conversations_matter_fk
    foreign key (converted_to_matter_id)
    references public.matters (id)
    on delete set null
);

create table if not exists public.ask_leo_conversation_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null,
  organisation_id uuid not null,
  user_id uuid not null,
  role text not null,
  content text not null,
  client_message_id text null,
  created_at timestamptz not null default now(),
  constraint ask_leo_conversation_messages_conversation_fk
    foreign key (conversation_id)
    references public.ask_leo_conversations (id)
    on delete cascade,
  constraint ask_leo_conversation_messages_role_check
    check (role in ('user', 'leo')),
  constraint ask_leo_conversation_messages_content_not_blank
    check (length(trim(content)) > 0)
);

create index if not exists ask_leo_conversations_owner_last_message_idx
  on public.ask_leo_conversations (organisation_id, user_id, last_message_at desc);

create index if not exists ask_leo_conversations_converted_idx
  on public.ask_leo_conversations (converted_to_matter_at);

create index if not exists ask_leo_conversation_messages_conversation_created_idx
  on public.ask_leo_conversation_messages (conversation_id, created_at asc, id asc);

create unique index if not exists ask_leo_conversation_messages_dedupe_idx
  on public.ask_leo_conversation_messages (conversation_id, role, client_message_id)
  where client_message_id is not null;

alter table public.matter_messages
  add column if not exists source_ask_leo_conversation_id bigint null,
  add column if not exists source_ask_leo_message_id bigint null;

create unique index if not exists matter_messages_source_ask_leo_message_uidx
  on public.matter_messages (source_ask_leo_message_id)
  where source_ask_leo_message_id is not null;

create index if not exists matter_messages_source_ask_leo_conversation_idx
  on public.matter_messages (source_ask_leo_conversation_id)
  where source_ask_leo_conversation_id is not null;

alter table public.ask_leo_conversations enable row level security;
alter table public.ask_leo_conversation_messages enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ask_leo_conversations'
      and policyname = 'ask_leo_conversations_select_own'
  ) then
    create policy ask_leo_conversations_select_own
      on public.ask_leo_conversations
      for select
      using (
        user_id = auth.uid()
        and organisation_id = public.leo_current_organisation_id()
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ask_leo_conversations'
      and policyname = 'ask_leo_conversations_insert_own'
  ) then
    create policy ask_leo_conversations_insert_own
      on public.ask_leo_conversations
      for insert
      with check (
        user_id = auth.uid()
        and organisation_id = public.leo_current_organisation_id()
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ask_leo_conversations'
      and policyname = 'ask_leo_conversations_update_own'
  ) then
    create policy ask_leo_conversations_update_own
      on public.ask_leo_conversations
      for update
      using (
        user_id = auth.uid()
        and organisation_id = public.leo_current_organisation_id()
      )
      with check (
        user_id = auth.uid()
        and organisation_id = public.leo_current_organisation_id()
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ask_leo_conversation_messages'
      and policyname = 'ask_leo_conversation_messages_select_own'
  ) then
    create policy ask_leo_conversation_messages_select_own
      on public.ask_leo_conversation_messages
      for select
      using (
        user_id = auth.uid()
        and organisation_id = public.leo_current_organisation_id()
        and exists (
          select 1
          from public.ask_leo_conversations c
          where c.id = ask_leo_conversation_messages.conversation_id
            and c.user_id = auth.uid()
            and c.organisation_id = public.leo_current_organisation_id()
        )
      );
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'ask_leo_conversation_messages'
      and policyname = 'ask_leo_conversation_messages_insert_own'
  ) then
    create policy ask_leo_conversation_messages_insert_own
      on public.ask_leo_conversation_messages
      for insert
      with check (
        user_id = auth.uid()
        and organisation_id = public.leo_current_organisation_id()
        and exists (
          select 1
          from public.ask_leo_conversations c
          where c.id = ask_leo_conversation_messages.conversation_id
            and c.user_id = auth.uid()
            and c.organisation_id = public.leo_current_organisation_id()
        )
      );
  end if;
end
$$;
