-- Ask Leo Employer Support foundation.
-- Adds explicit organisation ownership to Matters and introduces one-off Matter purchases.
-- Existing full-Leo behaviour is preserved: historical Matters are backfilled from their linked employee.

alter table public.matters
  add column if not exists organisation_id bigint null;

update public.matters m
set organisation_id = e.organisation_id
from public.employees e
where m.organisation_id is null
  and m.employee_id = e.id;

create index if not exists matters_organisation_id_idx
  on public.matters (organisation_id);

-- Employer Support access is deliberately separate from leo_organisation_entitlements.
-- An Employer Support account must not accidentally acquire full-platform access.
create table if not exists public.leo_employer_support_accounts (
  id bigint generated by default as identity primary key,
  organisation_id bigint not null references public.organisations(id) on delete cascade,
  status text not null default 'active'
    check (status in ('active','suspended','closed')),
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  closed_at timestamptz null,
  unique (organisation_id)
);

create table if not exists public.leo_employer_support_purchases (
  id bigint generated by default as identity primary key,
  organisation_id bigint not null references public.organisations(id) on delete cascade,
  account_id bigint not null references public.leo_employer_support_accounts(id) on delete cascade,
  matter_id bigint null references public.matters(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending','paid','provisioned','refunded','cancelled')),
  currency text not null default 'gbp',
  amount_minor integer null check (amount_minor is null or amount_minor >= 0),
  initial_issue text null,
  stripe_checkout_session_id text null,
  stripe_payment_intent_id text null,
  purchased_by uuid not null references auth.users(id) on delete restrict,
  purchased_at timestamptz null,
  provisioned_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (stripe_checkout_session_id),
  unique (stripe_payment_intent_id),
  unique (matter_id)
);

create index if not exists leo_employer_support_purchases_org_idx
  on public.leo_employer_support_purchases (organisation_id, created_at desc);

alter table public.leo_employer_support_accounts enable row level security;
alter table public.leo_employer_support_purchases enable row level security;

drop policy if exists leo_employer_support_accounts_select_members on public.leo_employer_support_accounts;
create policy leo_employer_support_accounts_select_members
on public.leo_employer_support_accounts
for select
to authenticated
using (
  exists (
    select 1
    from public.organisation_memberships om
    where om.organisation_id = leo_employer_support_accounts.organisation_id
      and om.user_id = auth.uid()
      and om.membership_status in ('active','accepted')
      and (om.access_starts_at is null or om.access_starts_at <= now())
      and (om.access_ends_at is null or om.access_ends_at >= now())
  )
);

drop policy if exists leo_employer_support_purchases_select_members on public.leo_employer_support_purchases;
create policy leo_employer_support_purchases_select_members
on public.leo_employer_support_purchases
for select
to authenticated
using (
  exists (
    select 1
    from public.organisation_memberships om
    where om.organisation_id = leo_employer_support_purchases.organisation_id
      and om.user_id = auth.uid()
      and om.membership_status in ('active','accepted')
      and (om.access_starts_at is null or om.access_starts_at <= now())
      and (om.access_ends_at is null or om.access_ends_at >= now())
  )
);

-- Writes to Employer Support account/purchase records are intentionally server-side only.
-- Stripe webhook provisioning will use the service role after validating the signed event.
revoke insert, update, delete on public.leo_employer_support_accounts from authenticated;
revoke insert, update, delete on public.leo_employer_support_purchases from authenticated;

comment on table public.leo_employer_support_accounts is
  'Persistent Employer Support account for an organisation. Separate from full Leo subscription entitlements.';

comment on table public.leo_employer_support_purchases is
  'One-off Employer Support Matter purchases. One successful purchase provisions at most one Matter.';

comment on column public.leo_employer_support_purchases.initial_issue is
  'Pre-purchase issue description carried into the paid Matter only after payment is confirmed.';

comment on column public.matters.organisation_id is
  'Explicit tenant owner for Matter isolation. Employer Support Matters must always populate this value.';
